services:
  telebox:
    image: wsng911/telebox:2.0
    container_name: telebox
    restart: unless-stopped
    volumes:
      - ./session:/app/my_session     # 登录 session（持久化）
      - ./plugins:/app/plugins        # 用户插件（持久化）
      - ./.env:/app/.env              # 配置文件
    stdin_open: true
    tty: true
